import { useEffect, useMemo, useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { ArrowUpRight, ChevronRight, Menu, Moon, Search, Sun, X } from 'lucide-react'
import { categories, getStory, liveUpdates, stories } from './data/news'
import { fetchLatestNews } from './services/newsService'
import './App.css'

const Logo = ({ light = false }) => <Link className={`logo ${light ? 'logo-light' : ''}`} to="/"><span className="logo-mark">◒</span><span><strong>DAILY VIEW</strong><small>SEE THE BIGGER PICTURE.</small></span></Link>
const Ticker = () => <div className="ticker"><div className="ticker-inner"><span><i /> LIVE</span><b>Global markets respond to latest economic developments</b><span><i /> LIVE</span><b>Global markets respond to latest economic developments</b></div></div>
const SectionHead = ({ eyebrow, title, note }) => <div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{note && <p>{note}</p>}</div>

function AppShell() {
  const [dark, setDark] = useState(false), [menuOpen, setMenuOpen] = useState(false), [searchOpen, setSearchOpen] = useState(false), [loading, setLoading] = useState(true)
  const location = useLocation()
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light' }, [dark])
  useEffect(() => { setMenuOpen(false); window.scrollTo(0, 0) }, [location.pathname])
  useEffect(() => { const timer = setTimeout(() => setLoading(false), 900); return () => clearTimeout(timer) }, [])
  if (loading) return <div className="loading-screen"><Logo light /><p>SEE THE BIGGER PICTURE.</p><span /></div>
  return <div className="app"><header className="nav-wrap"><nav className="nav container"><Logo /><div className="nav-links">{categories.map((category) => <Link key={category} to={`/${category.toLowerCase()}`}>{category}</Link>)}</div><div className="nav-actions"><button aria-label="Search" onClick={() => setSearchOpen(true)}><Search size={17} /></button><Link className="live-link" to="/live"><i /> LIVE</Link><button aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu size={19} /></button></div></nav></header><Ticker /><main><Routes><Route path="/" element={<Home />} /><Route path="/live" element={<Live />} /><Route path="/search" element={<SearchPage />} /><Route path="/:category" element={<Category />} /><Route path="/story/:id" element={<Article />} /></Routes></main><Footer />{menuOpen && <MobileMenu close={() => setMenuOpen(false)} />}{searchOpen && <SearchOverlay close={() => setSearchOpen(false)} />}</div>
}

function Home() { const [feed, setFeed] = useState(stories); useEffect(() => { fetchLatestNews().then((latest) => { if (latest.length) setFeed(latest) }) }, []); const hero = feed[0]; return <><section className="hero container"><div className="hero-image" style={{ backgroundImage: `url(${hero.image})` }} /><div className="hero-copy"><span className="eyebrow light-text">{hero.category}</span><h1>{hero.title}</h1><p>{hero.description}</p><div className="story-meta light-text"><span>{hero.date}</span><span>{hero.readTime}</span></div><Link className="text-link light-text" to={`/story/${hero.id}`}>Read full story <ArrowUpRight size={17} /></Link></div><div className="hero-caption">01 / 07 <span>Updated just now</span></div></section><section className="side-stories container"><div className="side-intro"><span className="eyebrow">Editor's note</span><p>Perspective is a practice. We bring you the context behind the headline, every day.</p><Link className="text-link" to="/technology">Explore the view <ArrowUpRight size={16} /></Link></div>{feed.slice(1, 3).map((story, index) => <StoryRow key={story.id} story={story} number={`0${index + 2}`} />)}</section><section className="section container world-section"><SectionHead eyebrow="The daily edit" title="Today's world" note="The stories shaping the day." /><div className="world-grid"><StoryFeature story={feed[1] || feed[0]} /><div className="world-stack">{feed.slice(2, 4).map((story, i) => <StoryRow key={story.id} story={story} number={`0${i + 2}`} />)}</div></div></section><Trending /><section className="section container latest"><SectionHead eyebrow="A running record" title="The latest" note="News moves quickly. Here is where it stands." /><div className="timeline">{feed.slice(0, 5).map((story) => <TimelineStory key={story.id} story={story} />)}</div></section><section className="section feature-band"><div className="container"><SectionHead eyebrow="Selected reading" title="Beyond the headline" note="Long reads, sharp ideas, and the details worth staying with." /><div className="feature-grid">{feed.slice(3, 6).map((story) => <StoryFeature key={story.id} story={story} compact />)}</div></div></section><Newsletter /></> }
const StoryFeature = ({ story, compact = false }) => <Link className={`story-feature ${compact ? 'compact' : ''}`} to={`/story/${story.id}`}><div className="feature-image"><img src={story.image} alt="" loading="lazy" /></div><div className="feature-copy"><span className="eyebrow">{story.category}</span><h3>{story.title}</h3><p>{story.description}</p><span className="text-link">Continue reading <ArrowUpRight size={15} /></span></div></Link>
const StoryRow = ({ story, number }) => <Link className="story-row" to={`/story/${story.id}`}><span className="story-number">{number}</span><img src={story.image} alt="" loading="lazy" /><div><span className="eyebrow">{story.category}</span><h3>{story.title}</h3><small>{story.time} · {story.readTime}</small></div><ChevronRight size={18} /></Link>
const TimelineStory = ({ story }) => <Link className="timeline-story" to={`/story/${story.id}`}><time>{story.time}</time><div><span className="eyebrow">{story.category}</span><h3>{story.title}</h3><p>{story.description}</p></div><ArrowUpRight size={18} /></Link>
const Trending = () => <section className="trending"><div className="container trending-head"><SectionHead eyebrow="In conversation" title="Trending now" /><span>Drag to explore <ChevronRight size={16} /></span></div><div className="trend-track">{['Artificial Intelligence', 'Global Economy', 'Cricket', 'Space Exploration', 'Cinema', 'The New India'].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</div></section>
function Category() { const { category = 'world' } = useParams(); const title = category.charAt(0).toUpperCase() + category.slice(1); const items = stories.filter((story) => story.category.toLowerCase() === category.toLowerCase()); const fallback = items.length ? items : stories.slice(0, 4); return <div className="category-page container"><div className="category-title"><span className="eyebrow">Daily View / Section</span><h1>{title}</h1><p>Stories and ideas with room for the nuance.</p></div><div className="category-lead"><StoryFeature story={fallback[0]} /><div className="category-list">{fallback.slice(1).map((story, i) => <StoryRow key={story.id} story={story} number={`0${i + 2}`} />)}</div></div><SectionHead eyebrow="More from this section" title="Latest" /><div className="feature-grid">{stories.filter((story) => !fallback.includes(story)).slice(0, 3).map((story) => <StoryFeature key={story.id} story={story} compact />)}</div></div> }
function Article() { const { id } = useParams(); const story = getStory(id); return <article className="article container"><div className="article-header"><span className="eyebrow">{story.category}</span><h1>{story.title}</h1><p className="article-dek">{story.description} This is the larger context behind a story still unfolding, told with clarity and care.</p><div className="byline">BY {story.author.toUpperCase()} <span>{story.date}</span><span>{story.readTime}</span></div></div><img className="article-hero" src={story.image} alt="" /><div className="article-layout"><aside>IN THIS STORY<br /><span>Context<br />The bigger picture<br />What comes next</span></aside><div className="article-body"><p className="lead">Some stories arrive as a sudden interruption. Others gather slowly, in the background, until the world looks a little different.</p><p>{story.description} Across the people and places at the center of this story, the same question keeps returning: what does progress look like when we can see its consequences in real time?</p><blockquote>“The biggest changes often begin quietly.”</blockquote><h2>A closer look at the moment</h2><p>The details matter. They give shape to the headline and make room for the voices that are easy to miss. Daily View follows those details, connecting the immediate update to the longer arc.</p><p>For now, the direction is clear, even if the outcome is not. The next chapter will be written by the choices made in the days ahead.</p></div></div></article> }
function Live() { return <div className="live-page container"><div className="category-title"><span className="eyebrow live-label"><i /> Live newsroom</span><h1>Live news</h1><p>Updates as they happen, with context close behind.</p></div><div className="live-layout"><div className="live-feed">{liveUpdates.map(([time, text]) => <div className="live-item" key={time}><time>{time}</time><div><span className="eyebrow">Just in</span><h2>{text}</h2><p>Our editors are following this story. More information will be added as it is confirmed.</p></div></div>)}</div><aside className="live-aside"><span className="eyebrow">On the desk</span><h3>Today in five minutes</h3><p>A considered briefing of the day's most important stories, delivered at 7AM.</p><button className="button-dark">Listen now <ArrowUpRight size={15} /></button></aside></div></div> }
function SearchPage() { const [query, setQuery] = useState(''); const results = useMemo(() => stories.filter((story) => `${story.title} ${story.category}`.toLowerCase().includes(query.toLowerCase())), [query]); return <div className="search-page container"><span className="eyebrow">Find a story</span><h1>Search Daily View</h1><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="What are you looking for?" />{query && <div className="search-results">{results.map((story) => <StoryRow story={story} number="↳" key={story.id} />)}{!results.length && <p>No stories found. Try another phrase.</p>}</div>}</div> }
const Newsletter = () => <section className="newsletter"><div className="container newsletter-inner"><div><span className="eyebrow">The daily brief</span><h2>Start your day informed.</h2><p>Get the stories that matter, delivered directly to your inbox.</p></div><form onSubmit={(event) => event.preventDefault()}><input aria-label="Email address" type="email" placeholder="Your email address" required /><button type="submit">Subscribe <ArrowUpRight size={16} /></button></form></div></section>
const Footer = () => <footer className="footer"><div className="container footer-grid"><Logo light /><div><span>Explore</span>{categories.map((category) => <Link key={category} to={`/${category.toLowerCase()}`}>{category}</Link>)}</div><div><span>Company</span><a href="#about">About</a><a href="#contact">Contact</a><a href="#privacy">Privacy</a></div><div><span>Follow</span><a href="#instagram">Instagram</a><a href="#x">X / Twitter</a><a href="#linkedin">LinkedIn</a></div></div><div className="container footer-bottom">© 2026 DAILY VIEW. ALL RIGHTS RESERVED.<span>SEE THE BIGGER PICTURE.</span></div></footer>
const MobileMenu = ({ close }) => <div className="overlay menu-overlay"><button className="close" onClick={close} aria-label="Close menu"><X /></button><Logo light /><div className="mobile-links">{['Home', ...categories].map((item) => <Link key={item} onClick={close} to={item === 'Home' ? '/' : `/${item.toLowerCase()}`}>{item}</Link>)}</div></div>
const SearchOverlay = ({ close }) => <div className="overlay search-overlay"><button className="close" onClick={close} aria-label="Close search"><X /></button><span className="eyebrow">Daily View / Search</span><h2>What are you looking for?</h2><form onSubmit={(event) => { event.preventDefault(); close() }}><input autoFocus placeholder="Search stories, topics, or ideas" /><button aria-label="Submit search"><ArrowUpRight /></button></form><p>Press ESC to close</p></div>
function App() { return <BrowserRouter><AppShell /></BrowserRouter> }
export default App
